### ISSUE TITLE
Exclusion not always effective

### ISSUE THREAD

**Issue by Menphis88** [KaiKikuchi/BetterOntime#2]
My idea is to have a setup where my 9 groups/ranks get a different amount of points each 10 minutes.
To test it i have made a single command that gave me enjin points every 10 minutes, and excluded all other groups but my own.
But once in a while, it seems to ignore the exclusion and run the commands on the other players.

I am not really sure if its a timing issue with groupmanagers autosaving, but i desyncing them and it still happens.

**Comment by KaiKikuchi** [comment]
You should test with something else than giving enjin points.
I used "msgraw KaiNoMood [bot debug] {p.name} test".

Anyway, it could be something related to your permission manager (like players loose their permissions for some second)
We're using pex, and it works very well. If you use inheritance, remember you can deny a permission with /pex group RankGroup add -betterontime.exclude.[id]
