### ISSUE TITLE
BetterOntime Issue

### ISSUE THREAD

**Issue by FriedRyan** [KaiKikuchi/BetterOntime#3]
I am trying to switch from ontime to BetterOntime hoping that it will be better for the server, and I can't get the plugin to work. I have uploaded it and the UUID plugin, but I get this in the console:

31.12 02:18:46 [Server] INFO -Fox_Glitz_YT
31.12 02:18:46 [Server] INFO ElCrprl: Still
31.12 02:18:46 [Server] INFO CONSOLE issued server command: /list 
31.12 02:18:46 [Server] INFO Admins: [Admin]~Duck2016+, [Owner]~Ryan2016+
31.12 02:18:46 [Server] INFO ChatMod: [ChatMod]~Panada+
31.12 02:18:46 [Server] INFO Member: _Archmage+, _ChronicGama_, Aldoseminecraft+, Amberstaryou+, AssassinJoel+, Blahbfish, Blue_Crystal03, Bri_Eli+, C0LT0NM, CraftyGurl8, DEMOdarthmalak+, ElCrprl, Grayson_+, ItzSkyPvP_+, KadenV, kittycatraine, kk21miner, Krystal_Sakura, LittleV07, Pikachu_42, PyschoGamzee, r0cker2684+, ThePerryJane+, weetabixgod+, Wolfe10+, WolfShadowdemon+
31.12 02:18:46 [Server] INFO Premium: [Premium]~MLGPando+
31.12 02:18:48 [Server] INFO ElCrprl: I wanna come
31.12 02:18:49 [Server] INFO r0cker2684 issued server command: /r I wont, trust me
31.12 02:18:49 [Server] INFO ElCrprl: :D
31.12 02:18:50 [Server] INFO _ChronicGama_ issued server command: /msg Blue_Crystal03 wanna marry
31.12 02:18:51 [Server] INFO [Premium]~MLGPando+: And I get caught for tecting in class
31.12 02:18:53 [Server] INFO CraftyGurl8: i need two diamonds!
31.12 02:18:54 [Server] INFO ElCrprl issued server command: /warp school
31.12 02:18:56 [Server] INFO [Premium]~MLGPando+: Texting*
31.12 02:18:59 [Server] INFO r0cker2684+: THIS IS A GOOD ONE XD
31.12 02:19:04 [Server] INFO CraftyGurl8: i need two diamonds!
31.12 02:19:06 [Server] INFO _Archmage issued server command: /warp shop
31.12 02:19:08 [Server] INFO [Premium]~MLGPando+: And the teacher says "Hand over the phone"
31.12 02:19:11 [Server] INFO Blahbfish issued server command: /msg Wolfe10 have you ever played t or d on this server? I always see ppl playing it but idk if its-
31.12 02:19:11 [Server] INFO UUID of player IoLuFlo is 695c985d-4387-4889-b846-ca7f8e208ee2
31.12 02:19:12 [Connect] User IoLuFlo, IP 2.216.143.64
31.12 02:19:12 [Server] INFO +IoLuFlo
31.12 02:19:12 [Server] INFO [GAListener] Player: IoLuFlo has 0 votes
31.12 02:19:12 [Multicraft] IoLuFlo ran command Message of the Day
31.12 02:19:14 [Server] INFO FriedRyan issued server command: /bot
31.12 02:19:14 [Server] WARN Exception in thread "pool-16-thread-8" 
31.12 02:19:14 [Server] WARN java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 02:19:14 [Server] WARN at net.kaikk.mc.bot.CommandExec$2.run(CommandExec.java:352)
31.12 02:19:14 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
31.12 02:19:14 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
31.12 02:19:14 [Server] WARN at java.lang.Thread.run(Thread.java:745)
31.12 02:19:15 [Server] INFO ElCrprl issued server command: /home
31.12 02:19:18 [Server] INFO FriedRyan issued server command: /bot reload
31.12 02:19:18 [Server] INFO [BetterOntime] Disabling BetterOntime v1.6.1
31.12 02:19:18 [Server] INFO [BetterOntime] Enabling BetterOntime v1.6.1
31.12 02:19:18 [Server] ERROR Error occurred while enabling BetterOntime v1.6.1 (Is it up to date?)
31.12 02:19:18 [Server] INFO java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 02:19:18 [Server] INFO at net.kaikk.mc.bot.DataStore.<init>(DataStore.java:129) ~[?:?]
31.12 02:19:18 [Server] INFO at net.kaikk.mc.bot.BetterOntime.onEnable(BetterOntime.java:35) ~[?:?]
31.12 02:19:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.kaikk.mc.bot.CommandExec.reload(CommandExec.java:133) [BetterOntime-1.6.1.jar:?]
31.12 02:19:18 [Server] INFO at net.kaikk.mc.bot.CommandExec.onCommand(CommandExec.java:60) [BetterOntime-1.6.1.jar:?]
31.12 02:19:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
31.12 02:19:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 02:19:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
31.12 02:19:18 [Server] INFO Blahbfish issued server command: /msg Wolfe10 any fun :/
31.12 02:19:19 [Server] INFO [Premium]~MLGPando+: SO I write phone on a peice of paper and give it to her
31.12 02:19:20 [Server] INFO kk21miner issued server command: /msg itzskypvp look i never said anything bad in the call
31.12 02:19:21 [Server] INFO CONSOLE issued server command: /list 
31.12 02:19:21 [Server] INFO Admins: [Admin]~Duck2016+, [Owner]~Ryan2016+
31.12 02:19:21 [Server] INFO ChatMod: [ChatMod]~Panada+
31.12 02:19:21 [Server] INFO Member: _Archmage+, _ChronicGama_, Aldoseminecraft+, Amberstaryou+, AssassinJoel+, Blahbfish, Blue_Crystal03, Bri_Eli+, C0LT0NM, CraftyGurl8, DEMOdarthmalak+, ElCrprl, Grayson_+, IoLuFlo, ItzSkyPvP_+, KadenV, kittycatraine, kk21miner, Krystal_Sakura, LittleV07, Pikachu_42, PyschoGamzee, r0cker2684+, ThePerryJane+, weetabixgod+, Wolfe10+, WolfShadowdemon+
31.12 02:19:21 [Server] INFO Premium: [Premium]~MLGPando+
31.12 02:19:22 [Server] INFO Wolfe10 issued server command: /r no, i havent
31.12 02:19:23 [Server] INFO [Premium]~MLGPando+: Then she says
31.12 02:19:24 [Server] INFO Amberstaryou issued server command: /island view
31.12 02:19:25 [Server] INFO kittycatraine: whats gonna happen
31.12 02:19:25 [Server] INFO FriedRyan issued server command: /bot help

**Comment by KaiKikuchi** [comment]
Hello. Please be sure to use the latest version of BetterOntime (v1.7.1) and UUIDProvider (v.2.1)
Be sure to put both jar files to the plugins folder. Also configure UUIDProvider's MySQL database (check config.yml under UUIDProvider folder). BetterOntime requires a database too.

**Comment by FriedRyan** [comment]
I have the latest builds and they are connected to mysql.

:02:44 [Multicraft] Skipped 28 lines due to rate limit (30/s)
31.12 16:02:44 [Server] INFO UUID of player Hex_Apollo is 347b41ce-6eab-45e8-b8c9-03841fff8312
31.12 16:02:44 [Server] INFO +harmonybear101
31.12 16:02:44 [Server] INFO +kaneki_ken_CRAZY
31.12 16:02:44 [Server] ERROR Could not pass event PlayerLoginEvent to BetterOntime v1.7.1
31.12 16:02:44 [Server] INFO org.bukkit.event.EventException
31.12 16:02:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
31.12 16:02:44 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 16:02:44 [Server] INFO at net.kaikk.mc.bot.EventListener.onPlayerLogin(EventListener.java:50) ~[?:?]
31.12 16:02:44 [Server] INFO at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
31.12 16:02:44 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
31.12 16:02:44 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
31.12 16:02:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:44 [Server] INFO ... 13 more
31.12 16:02:45 [Connect] User Unidaro, IP 46.9.201.119
31.12 16:02:45 [Multicraft] Unidaro ran command Message of the Day
31.12 16:02:45 [Server] ERROR Could not pass event PlayerLoginEvent to BetterOntime v1.7.1
31.12 16:02:45 [Server] INFO org.bukkit.event.EventException
31.12 16:02:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:45 [Multicraft] Skipped 26 lines due to rate limit (30/s)
31.12 16:02:45 [Server] INFO UUID of player kk21miner is 6a8ed204-963a-4668-924b-185b7b8fde82
31.12 16:02:46 [Server] ERROR Could not pass event PlayerLoginEvent to BetterOntime v1.7.1
31.12 16:02:46 [Server] INFO org.bukkit.event.EventException
31.12 16:02:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
31.12 16:02:46 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 16:02:46 [Server] INFO at net.kaikk.mc.bot.EventListener.onPlayerLogin(EventListener.java:50) ~[?:?]
31.12 16:02:46 [Server] INFO at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
31.12 16:02:46 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
31.12 16:02:46 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
31.12 16:02:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 16:02:46 [Server] INFO ... 13 more

**Comment by KaiKikuchi** [comment]
Check the server log while the server is starting. You should see "Loading UUIDProvider..."

**Comment by FriedRyan** [comment]
[UUIDProvider] Unable to read database data. Details: 
Unknown column 'lastcheck' in 'where clause'

**Comment by FriedRyan** [comment]
Yeah I am still getting stuff like this:



31.12 22:56:21 [Server] ERROR Could not pass event PlayerLoginEvent to BetterOntime v1.7.1
31.12 22:56:21 [Server] INFO org.bukkit.event.EventException
31.12 22:56:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:22 [Multicraft] Skipped 93 lines due to rate limit (30/s)
31.12 22:56:22 [Server] INFO zcrasher issued server command: /msg Ramo sorry love you but i need to go see u tomorrow! :)
31.12 22:56:22 [Server] INFO epicoolweiss issued server command: /island tp PVP_S
31.12 22:56:23 [Server] INFO TrollSister_6_9 issued server command: /r why are u sad againnn
31.12 22:56:24 [Server] INFO Leonardo_games issued server command: /list
31.12 22:56:25 [Server] INFO CrazlyBunny issued server command: /home
31.12 22:56:25 [Server] INFO xX_PotatoPvP_Xx issued server command: /msg Zhice
31.12 22:56:26 [Disconnect] User PolarGirlRock has disconnected, reason: Disconnected
31.12 22:56:26 [Server] ERROR Could not pass event PlayerQuitEvent to BetterOntime v1.7.1
31.12 22:56:26 [Server] INFO org.bukkit.event.EventException
31.12 22:56:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
31.12 22:56:26 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 22:56:26 [Server] INFO at net.kaikk.mc.bot.EventListener.onPlayerQuit(EventListener.java:68) ~[?:?]
31.12 22:56:26 [Server] INFO at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
31.12 22:56:26 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
31.12 22:56:26 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
31.12 22:56:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:26 [Server] INFO ... 12 more
31.12 22:56:36 [Server] INFO -PolarGirlRock
31.12 22:56:36 [Disconnect] User Kempy_Senpai has disconnected, reason: Disconnected
31.12 22:56:36 [Server] ERROR Could not pass event PlayerQuitEvent to BetterOntime v1.7.1
31.12 22:56:36 [Server] INFO org.bukkit.event.EventException
31.12 22:56:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
31.12 22:56:36 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/kaikk/mc/uuidprovider/UUIDProvider
31.12 22:56:36 [Server] INFO at net.kaikk.mc.bot.EventListener.onPlayerQuit(EventListener.java:68) ~[?:?]
31.12 22:56:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
31.12 22:56:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
31.12 22:56:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
31.12 22:56:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.12 22:56:36 [Server] INFO ... 12 more

**Comment by FriedRyan** [comment]
When I do /plugins, it shows UUIDProvider in red so I am guessing that is it.

**Comment by KaiKikuchi** [comment]
Try deleting uuidprovider's database table "uuidcache". Then restart your server.

**Comment by FriedRyan** [comment]
Awesome. It worked, thanks!
